modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
issueTrackerURL="https://github.com/SilentChaos512/Token-Enchanter/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/token-enchanter"
#logoFile="examplemod.png" #optional
credits=""
authors="SilentChaos512"

[[mods]]
    modId="tokenenchanter"
    version="${file.jarVersion}"
    displayName="Token Enchanter"
    updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/Token-Enchanter/1.17.x/update.json"
    description='''
    Downloads: https://www.curseforge.com/minecraft/mc-mods/token-enchanter (I do not upload anywhere else)
    Changelog: https://github.com/SilentChaos512/Token-Enchanter/blob/1.17.x/CHANGELOG.md
    Source: https://github.com/SilentChaos512/Token-Enchanter/
    Issues: https://github.com/SilentChaos512/Token-Enchanter/issues
    '''

[[dependencies.tokenenchanter]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tokenenchanter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tokenenchanter]]
    modId="silentlib"
    mandatory=true
    versionRange="[5.0,6.0)"
    ordering = "NONE"
    side = "BOTH"