@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.tokenenchanter.config;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;