@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.tokenenchanter.loot.function;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;