@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.tokenenchanter.api.xp;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;