@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.tokenenchanter.block.tokenenchanter;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;