@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.tokenenchanter.loot;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;